# Generated by Django 3.1.2 on 2020-10-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20201025_1703'),
        ('tray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.businessmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.tablemodel'),
        ),
    ]
