# Generated by Django 3.1.2 on 2020-10-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0004_auto_20201027_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('U', 'Unplaced'), ('PL', 'Placed'), ('S', 'Serving'), ('P', 'Paid')], default='Unplaced', max_length=2),
        ),
    ]
