# Generated by Django 3.1.2 on 2020-11-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0007_auto_20201114_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
