# Generated by Django 3.1.2 on 2020-12-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0048_auto_20201203_0018'),
        ('tray', '0012_auto_20201201_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.tablemodel'),
        ),
    ]
