# Generated by Django 3.1.2 on 2021-01-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tray', '0013_auto_20201206_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
