# Generated by Django 3.1.2 on 2020-11-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201113_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='currency',
            field=models.CharField(blank=True, default='-', max_length=3, null=True),
        ),
    ]
