# Generated by Django 3.1.2 on 2020-11-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201115_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='device',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
