# Generated by Django 3.1.2 on 2020-11-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201115_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='device',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
