# Generated by Django 3.1.2 on 2020-12-01 09:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201201_1100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='device',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
