# Generated by Django 3.1.2 on 2020-10-19 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_nr', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('all_tables', models.IntegerField()),
                ('available_tables', models.IntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
