# Generated by Django 3.1.2 on 2020-10-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='available_tables',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
