# Generated by Django 3.1.2 on 2020-10-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20201019_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='available_tables',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
