# Generated by Django 3.1.2 on 2020-10-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20201019_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='business_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='phone_nr',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
