# Generated by Django 3.1.2 on 2020-10-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_tablemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
