# Generated by Django 3.1.2 on 2020-10-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_tablemodel_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemodel',
            name='current_customer',
        ),
        migrations.RemoveField(
            model_name='tablemodel',
            name='is_available',
        ),
    ]
