# Generated by Django 3.1.2 on 2020-10-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20201025_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
