# Generated by Django 3.1.2 on 2020-11-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20201027_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('bar', 'Bar'), ('restaurant', 'Restaurant'), ('cafe', 'Café'), ('other', 'Other')], default='Other', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.businesscategory'),
        ),
    ]
