# Generated by Django 3.1.2 on 2020-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20201106_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
