# Generated by Django 3.1.2 on 2020-11-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_businesscategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategory',
            name='icon',
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.businesscategory'),
        ),
    ]
