# Generated by Django 3.1.2 on 2020-11-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20201106_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
