# Generated by Django 3.1.2 on 2020-11-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='icon',
            field=models.ImageField(blank=True, default='../../media/beer.png', null=True, upload_to=''),
        ),
    ]
