# Generated by Django 3.1.2 on 2020-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_productmodel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='icon',
            field=models.ImageField(blank=True, default='beer.png', null=True, upload_to=''),
        ),
    ]
