# Generated by Django 3.1.2 on 2020-11-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_auto_20201106_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='icon',
            field=models.ImageField(blank=True, default='media/beer.png', null=True, upload_to=''),
        ),
    ]
