# Generated by Django 3.1.2 on 2020-11-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_auto_20201106_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, default='beer.png', height_field=450, null=True, upload_to='', width_field=450),
        ),
    ]
