# Generated by Django 3.1.2 on 2020-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_auto_20201106_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, default='beer.png', null=True, upload_to=''),
        ),
    ]
