# Generated by Django 3.1.2 on 2020-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_auto_20201107_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='business_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
