# Generated by Django 3.1.2 on 2020-11-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_auto_20201108_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='service',
        ),
    ]
