# Generated by Django 3.1.2 on 2020-11-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_businessmodel_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessmodel',
            old_name='address',
            new_name='maps_address',
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='displayed_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
