# Generated by Django 3.1.2 on 2020-11-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_auto_20201115_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='all_tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.productcategory'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
