# Generated by Django 3.1.2 on 2020-11-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20201115_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='category_name',
            field=models.CharField(choices=[('bar', 'Bar'), ('restaurant', 'Restaurant'), ('cafe', 'Café'), ('club', 'Club'), ('other', 'Other')], default='Other', max_length=20),
        ),
    ]
