# Generated by Django 3.1.2 on 2020-11-29 18:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_auto_20201126_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='category_name',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Restaurant', 'Restaurant'), ('Café', 'Cafe'), ('Club', 'Club'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.CheckConstraint(check=models.Q(price__gt=Decimal('0')), name='price_gt_0'),
        ),
    ]
