# Generated by Django 3.1.2 on 2020-11-30 12:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_auto_20201129_2038'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmodel',
            name='price_gt_0',
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.CheckConstraint(check=models.Q(price__gte=Decimal('0')), name='price_gt_0'),
        ),
    ]
