# Generated by Django 3.1.2 on 2020-12-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_auto_20201130_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
