# Generated by Django 3.1.2 on 2020-12-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_auto_20201201_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
