# Generated by Django 3.1.2 on 2020-12-01 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_auto_20201201_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='business.businesscategory'),
        ),
    ]
