# Generated by Django 3.1.2 on 2020-12-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_auto_20201201_1147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablemodel',
            unique_together={('business', 'table_nr')},
        ),
    ]
