# Generated by Django 3.1.2 on 2020-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_auto_20201201_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
