# Generated by Django 3.1.2 on 2020-12-02 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0044_tablemodel_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='current_guests',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
