# Generated by Django 3.1.2 on 2020-12-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0048_auto_20201203_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablemodel',
            name='deleted',
        ),
    ]
