# Generated by Django 3.1.2 on 2020-12-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0049_remove_tablemodel_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('business', 'category_name')},
        ),
    ]
