# Generated by Django 3.1.2 on 2020-12-08 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0050_auto_20201207_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscategory',
            options={'verbose_name_plural': 'Business Category models'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Category models'},
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
