# Generated by Django 3.1.2 on 2020-12-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0052_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('A', 'Accepted'), ('D', 'Declined'), ('C', 'Canceled')], default='Sent', max_length=15),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessmodel')),
            ],
        ),
    ]
