# Generated by Django 3.1.2 on 2020-12-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0054_auto_20201226_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='')),
                ('belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
