# Generated by Django 3.1.2 on 2021-01-07 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0055_auto_20201226_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='current_guests',
            field=models.ManyToManyField(blank=True, related_name='current_guests', to=settings.AUTH_USER_MODEL),
        ),
    ]
