# Generated by Django 3.1.2 on 2021-01-10 18:48

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0056_auto_20210107_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='icon',
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=business.models.admin_images),
        ),
        migrations.AlterField(
            model_name='galleryimagemodel',
            name='source',
            field=models.ImageField(upload_to=business.models.gallery_image_up),
        ),
    ]
